### ISSUE TITLE
Invalid keys in migration telemetry?

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6729]
Franks says: I’m seeing a bunch of glean errors from the migration pings, mainly invalid values that are being attempted to be insert into the pings. Here’s a total count from one day:

```
key	invalid_count
migration.logins.failure_counts	29452
migration.bookmarks.migrated	13948
migration.history.migrated	13514
migration.logins.detected	7325
migration.open_tabs.detected	4184
migration.open_tabs.migrated	4182
migration.history.detected	913
```

Let's figure out what is going on here. Could be working as epxected or maybe 0 values?

**Comment by st3fan** [comment]
@grigoryk want to take a peek at this?

**Comment by grigoryk** [comment]
@st3fan so yeah, this is mostly harmless - here we're recording 0 values into a glean metric type which doesn't understand them. @fbertsch says it doesn't affect our dashboards as far as data analysis goes.

If we wanted to do this properly, for each metric where we _may_ have a legit 0 value (like a failure count), we'd need a separate boolean metric type to record its absence/presence. E.g., instead of `{"failures": 0}`, you'd have `{"any_failures": false}`, and `{"any_failures": true, failures: 5}`.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1626372 to make these sorts of things less cumbersome.

In the meantime, if this isn't affecting our dashboards, and extra bandwidth impact from having these errors in the ping is negligible (seems like it is), I'm not sure I see value in fixing the ping just for the sake of strict correctness. We'd need to change the ping itself, code which sets these values, get a data review, and then ship all of this into a release migration without any bake time on beta/nightly... I'd rather we just did nothing in this case.

cc @Dexterp37 for a second opinion on importance of fixing this.

**Comment by fbertsch** [comment]
Judging from what @grigoryk has told me, I can confirm that we don't need to change this to give any more info for analysis.

**Comment by Dexterp37** [comment]
> In the meantime, if this isn't affecting our dashboards, and extra bandwidth impact from having these errors in the ping is negligible (seems like it is), I'm not sure I see value in fixing the ping just for the sake of strict correctness.

"strict correctness" is not the point nor the problem. While we're in the process of handing over error checking to product owners (e.g. Fenix, Firefox Reality, etc.), the Glean SDK team looks at all the errors reported by products using Glean. This happens using custom dashboards that show us errors over time and their rate.

Given the number of metrics and the number of errors being reported, looking at these dashboards already requires some efforts. Having metrics reporting errors even though this could be fixed easily adds complexity where we really could do without ;-)

>  We'd need to change the ping itself, code which sets these values, get a data review, and then ship all of this into a release migration without any bake time on beta/nightly... I'd rather we just did nothing in this case.

No data review nor a new quick release is needed, but I'd rather see this fix before another Fennec to Fenix migration build is issued. The fix here should be as simple as, [for example](https://github.com/mozilla-mobile/android-components/blob/ce826afe401de818e5efcf5a281bf0564d6c5f2c/components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt#L817):

```
if (success.failedToProcess > 0) {
  MigrationLogins.failureCounts["process"].add(success.failedToProcess)
}
```

If you need proof that the code was running at all, then the boolean is needed as well. This needs to be done properly: the risk here is to make it harder for the SDK team to triage *real* errors and bugs in a timely manner.

**Comment by grigoryk** [comment]
Thanks for the Glean perspective, @Dexterp37.

Since absence of the `failure` count isn't negatively affecting our dashboards, the fix you suggested (without the `boolean`) should be sufficient. Note that we'll need to repeat it for every single "possibly 0" metric type we have, of which there are a few.
We'll consider this in our next triage.

However, what I don't quite understand is this: if this is such a problem for the glean team, why is this surfacing just now after we've migrated both Nightly and Beta channels? Also, can this problem be resolved in another way? For example, by adjusting queries which power those dashboards.

From the point of view of the migration effort, this is purely about risk mitigation. At this point, we have zero ability to test our migration changes on a non-release population, so going forward there's very little appetite for shipping changes which didn't get decent bake time on nightly and beta, or are absolutely necessary.

**Comment by Dexterp37** [comment]
> However, what I don't quite understand is this: if this is such a problem for the glean team, why is this surfacing just now after we've migrated both Nightly and Beta channels? 

Note that error monitoring is something that _I think_ product owners should do and that the Glean SDK team does, in addition to its tasks and duties. Looking at all the products, channels, variants and projects doesn't simply scale up on our end.

This didn't show up in the dashboards because we were looking at the Fenix app ids, not the Fennec ones. (now solved)

> Also, can this problem be resolved in another way? For example, by adjusting queries which power those dashboards.

In general, this is a misuse of a metric type outside of its documented behaviour. This should be fixed and the error stream is something you should not rely on to make decision, unless the decision is "Should we fix this problem now?". For example, what if the behaviour of the type changes a bit and, instead of reporting errors when setting 0, we'd just log to logcat?

Error reporting is only really meant to be used as a way to flag misuse of metric types.

> From the point of view of the migration effort, this is purely about risk mitigation. At this point, we have zero ability to test our migration changes on a non-release population, so going forward there's very little appetite for shipping changes which didn't get decent bake time on nightly and beta, or are absolutely necessary.

I'm not suggesting we do this _now_. I'm suggesting we do this next time a new build is created: are we planning to use a staged-release approach with Release as well? This change seems relatively low risk...

This is a data-quality problem and should be treated as such, IMHO :-)

**Comment by grigoryk** [comment]
> This change seems relatively low risk...
Agree.

At the same time, our migration telemetry isn't going to change going forward, works really well and is serving our needs (thanks to Glean!). The value of the change you're proposing (granted, trivial one - but these things tend to add-up and sometimes backfire) seems to be an easier detection of problems. At this point, we've rooted out/worked around any meaningful problems we've had. I'm pretty content with the end result. Do you still think this change may be valuable?

**Comment by Dexterp37** [comment]
> 
> 
> > This change seems relatively low risk...
> 
> Agree.
> 
> At the same time, our migration telemetry isn't going to change going forward, works really well and is serving our needs (thanks to Glean!). The value of the change you're proposing (granted, trivial one - but these things tend to add-up and sometimes backfire) seems to be an easier detection of problems. At this point, we've rooted out/worked around any meaningful problems we've had. I'm pretty content with the end result. Do you still think this change may be valuable?

If migration telemetry is touched again, I'd recommend adding this to the changes. If not, I think it's fine, given that this code is going to die anyway.. right? :)

**Comment by grigoryk** [comment]
Ok, thanks for clarification. I think we're in agreement here.

> given that this code is going to die anyway.. right? :)

As soon as possible, right after release is shipped :-) It'll be a great moment.

**Comment by ebalazs-sv** [comment]
@st3fan Hi! I see that this issue is not fixed for now, but if the telemetry code will be touched again, these changes are recommended to be added as well. Due to that, can this issue be moved to Backlog? Thanks!
